import type { Metadata } from 'next';

const AUTHOR = 'Gareth MacLeod';

/**
 * Link-preview metadata for an essay. The card image is a static PNG in
 * public/og/, generated by scripts/generate-og.mjs — regenerate when adding
 * a post. Absolute URLs are resolved against metadataBase in app/layout.tsx.
 */
export function postMetadata(post: {
  slug: string;
  title: string;
  description: string;
}): Metadata {
  const image = `/og/${post.slug}.png`;
  return {
    title: `${post.title} — ${AUTHOR}`,
    description: post.description,
    openGraph: {
      type: 'article',
      title: post.title,
      description: post.description,
      siteName: AUTHOR,
      url: `/writing/${post.slug}`,
      images: [{ url: image, width: 2400, height: 1260, alt: post.title }],
    },
    twitter: {
      card: 'summary_large_image',
      title: post.title,
      description: post.description,
      images: [image],
    },
  };
}
